[package]
name = "song"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4.0"
midly = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
typetag = "0.2.1"
dyn-clone = "1.0.8"
ron = "0.7.1"
serde_json = "1.0.82"
