[package]
name = "song"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4.0"
midly = "0.5.2"
once_cell = "1.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_traitobject = "0.2.7"
ron = "0.8.0"
dyn-clone = "1.0.9"
