[package]
name = "song"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4.0"
midly = "0.5.2"
once_cell = "1.13.1"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8.0"
serde_json = "1.0.85"
permutation = "0.4.1"
derive_more = "0.99.17"
